### ISSUE TITLE
The links in the documentatino for the AWS Go client is broken

### ISSUE THREAD

**Issue by Pisush** [Unknwon/gowalker#103]
e.g. [this link](https://gowalker.org/github.com/aws/aws-sdk-go/service/s3#ListObjectsV2Input_SetStartAfter) it leads [here](https://sourcegraph.com/go/github.com/aws/aws-sdk-go/-/ListObjectsV2Input/SetStartAfter)

Basically https://sourcegraph.com/go/github.com/aws/aws-sdk-go/ doesn't exist but
https://github.com/aws/aws-sdk-go/ does

**Comment by Unknwon** [comment]
Since the new version only shows the link to the repository home on sourcegraph.com, closing.
