### ISSUE TITLE
无闻老师求推荐！！！

### ISSUE THREAD

**Issue by zhouzhou84** [Unknwon/gowalker#111]
把无闻老师你的go语言基础视频看完了，最后一个是“项目与坑”，
老师你还有进阶视频资源吗？
以及go语言练手的项目，
go语言怎么和区块链结合使用呢？
求推荐啊啊~~
有telegram群吗？或是微信群？Line群？

**Comment by Unknwon** [comment]
额。。这个东西，修行靠个人，自己做项目踩坑才是进步最快的方式。缺什么搜什么，积累自然就起来了。
