### ISSUE TITLE
Consider adding a link to the equivalent godoc page

### ISSUE THREAD

**Issue by ddevault** [Unknwon/gowalker#113]
With much respect to your work, I don't really prefer this interface over godoc, and I'd rather click through to godoc when linked to this website from some project.

**Comment by Unknwon** [comment]
You can just use godoc.org

**Comment by ddevault** [comment]
That doesn't help when I run into a library which has chosen to link to gowalker from their readme.

**Comment by Unknwon** [comment]
Replace "gowalker.org" with "godoc.org" should work in browser address bar.

**Comment by ddevault** [comment]
If I sent a patch which adds what I'm asking for, would you merge it?

**Comment by Unknwon** [comment]
Nope.

**Comment by ddevault** [comment]
Whelp, good to know that there are still subversives in the Golang community.

**Comment by Unknwon** [comment]
You can always maintain your work and setup a website: https://gowalker2godoc.org . That should be super nice :joy:

**Comment by ddevault** [comment]
I'm not sure how that reads as anything other than defending your ego with fallacious exagerration. Be reasonable: what would be super nice would be accepting a simple patch which links your project with the official documentation for Golang.

**Comment by Unknwon** [comment]
The link should work, does not mean it guarantee to work. Once in the codebase, I'll be responsible for maintaining it, and that's not part of the goals of this project.

Doing something useful for yourself and others may need is not a super nice thing? 

FYI, I could have deleted this issue in the first place.

**Comment by ddevault** [comment]
>The link should work, does not mean it guarantees to work. Once in the codebase, I'll be responsible for maintaining it, and that's not part of the goals of this project.

While I normally empathise with this viewpoint as a maintainer of many projects myself, this pushes the bounds of logic. A godoc link is not a complex thing. And, I would happily volunteer to respond promptly to any bugs or issues during refactorings which bump into it, but in practice I expect that anyone refactoring will find themselves entirely unburdened by the cost of updating such a trivial feature.

Frankly your arguments are extremely thin and the real reason you don't want this is burningly obvious - and I wish you'd just state it outright instead of making excuses.

>FYI, I could have deleted this issue in the first place.

You still can.

**Comment by Unknwon** [comment]
You're right. Thanks for the lesson!
