### ISSUE TITLE
gowalker kept failing to refresh docs

### ISSUE THREAD

**Issue by panjf2000** [unknwon/gowalker#115]
gowalker 最近是出了什么问题吗？好像所有的仓库的文档都不能刷新了，一直失败，如下：
![image](https://user-images.githubusercontent.com/7496278/66767684-8c479880-eee3-11e9-9019-9599238b29e1.png)

**Comment by unknwon** [comment]
额。。我智障了，我前几天清理了一波令牌。。把 gowalker 的给删了，我今晚下班处理一下。

**Comment by unknwon** [comment]
解决了！感谢反馈。
