### ISSUE TITLE
增加用快捷键调出控制面板后按 "ESC" 关闭功能

### ISSUE THREAD

**Issue by dearlin** [Unknwon/gowalker#46]
现在调出控制面板后, 必须要用鼠标去关闭, 比较麻烦, 可以增加按 "ESC" 键关闭的 js 功能

**Comment by qzyuanmu** [comment]
哪个快捷键，看下视频是可以调出来的，网页上我测试没找到

**Comment by Unknwon** [comment]
@qzyuanmu 新版这个功能还没完成。。。

**Comment by Unknwon** [comment]
Fixed. 再次感谢反馈！
