### ISSUE TITLE
改版后的doc刷新功能？

### ISSUE THREAD

**Issue by Bluek404** [Unknwon/gowalker#56]
改版之后没找到在哪里刷新文档

是自动刷新么？

**Comment by Unknwon** [comment]
还在开发中。。。

**Comment by micln** [comment]
原来的版本已经清掉了么或者不兼容？

可不可以再加个老版本的入口方便一些功能的使用

**Comment by Unknwon** [comment]
@micln 其实我原本的想法是挺好的。。因为老版本超过1年没更新过代码了。。而且是第一个go项目代码丑陋不堪。。于是新写了个版本。。无奈我好懒。。给大家造成困扰了。。:joy:
