### ISSUE TITLE
不支持coding.net了？？

### ISSUE THREAD

**Issue by micln** [Unknwon/gowalker#58]
RT

**Comment by Unknwon** [comment]
..一直没支持。。不过会加进去 :smiley:

**Comment by micln** [comment]
以前我记得可以的

换风格之后还能用的

被*之后不知情几天没上再去的时候就不行了

**Comment by Unknwon** [comment]
@micln 好不容易换了新服务器结果悲剧的IP背墙了。。无奈又换了一次服务器。。现在应该可以访问了。

我会努力编码抓紧优先支持国内几个平台的 :beer:

**Comment by micln** [comment]
:beer:
