### ISSUE TITLE
Failed: golang.org/x/net/websocket

### ISSUE THREAD

**Issue by micln** [Unknwon/gowalker#59]
槽糕！大事不好了，快点跑路吧...
golang.org/x/net/websocket: check package: Package remote path does not match any service

我的本地也获取不到，但是c9上发现这个地址是正常的

**Comment by Unknwon** [comment]
多谢反馈。。我被自己的错误提示逗笑了。。

**Comment by Unknwon** [comment]
Fixed: https://gowalker.org/golang.org/x/net/websocket Thanks again!

**Comment by micln** [comment]
:smile:
