### ISSUE TITLE
Search with quotes and whitespace

### ISSUE THREAD

**Issue by nburns** [Unknwon/gowalker#68]
It would be really great if the go walker search strip extraneous characters in the search box.

For example, inputting (the leading whitespace is a tab character, and the import path is surrounded by quotes)
```
	"github.com/mitchellh/goamz/s3"
```
returns no results, but if I strip the whitespace and quotes myself and input
```
github.com/mitchellh/goamz/s3
```
I get the results i'm looking for.

**Comment by Unknwon** [comment]
Hi @nburns , thanks your feedback!

It is now possible on https://gowalker.org

**Comment by nburns** [comment]
Wow that was fast! Thanks!

**Comment by Unknwon** [comment]
:smile: just happened to be a easy fix.
