### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by joeblew99** [Unknwon/gowalker#72]
On a page that shows many repos add into the table the metrics for how many each imports or is imported by .

https://gowalker.org/github.com/boltdb/bolt?refs

For example it would be very useful if I could see the project with the highest number of imported by !
Add sorting also by this value would be even quicker for me.

I expect many users want this.

**Comment by Unknwon** [comment]
Thanks your feedback!

> For example it would be very useful if I could see the project with the highest number of imported by !
Add sorting also by this value would be even quicker for me.

Could you give more details on this? What does `highest number of imported by !` mean?
