### ISSUE TITLE
每次查看任一个文档都是生成“2周之前”

### ISSUE THREAD

**Issue by proudlily** [Unknwon/gowalker#76]
如题，虽然称不上是bug,但是强迫症总是受不了的。

**Comment by Unknwon** [comment]
瞎说，这个明明是三天前 https://gowalker.org/os

**Comment by proudlily** [comment]
我不知道生成的时间指的是什么？我对这个有疑惑。感觉不准确的样子。我理解的是，文档输入到后台，生成的时间。

**Comment by Unknwon** [comment]
文档生成的时间啊。。不是仓库更新的时候。。我觉得你发生错觉了。。:trollface:
